### ISSUE TITLE
Unknown but valid chunks should raise WARNING, not major or minor ERRORs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pngcheck-metanorma#1]
Reasoning: https://github.com/metanorma/pngcheck-ruby/issues/17#issuecomment-1258844258

Approach as discussed with @maxirmx :
> Based on your analisys I will patch pngcheck so that it will return STATUS_WARNING if a chunk of unknown type is found

Agree. I know this is not ideal but it's what is possible.

> In case of WARNING we have two options:
> 
> * ignore it and return true
> * raise exception but add status code field to it so that  it is possible to recover warnings upstream

The latter please.

**Comment by maxirmx** [comment]
There is obvious bug in the code.
When a chunk of unknown typw is found error is raised ```if (PUBLIC(chunkid)) ```
However, the standard says that ```An unknown chunk type is not treated as an error unless it is a critical chunk```, so the condition shall be ```if (PUBLIC(chunkid) && CRITICAL(chunkid))```

**Comment by ronaldtse** [comment]
Thanks for merging #3 !
