### ISSUE TITLE
Implement pngcheck => pngcheck-ruby release auto-update

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pngcheck-metanorma#4]
This task is to implement a GitHub Actions workflow for triggering a version update at pngcheck-ruby once there is a new version of pngcheck.

**Comment by CAMOBAP** [comment]
Both PRs are ready for review:
 - #6
 - https://github.com/metanorma/pngcheck-ruby/pull/26

**Comment by ronaldtse** [comment]
@CAMOBAP thank you! One issue -- can we accommodate updating the pngcheck-ruby version without changing pngcheck? (e.g. Ruby bug fix). Thanks!

**Comment by CAMOBAP** [comment]
> @CAMOBAP thank you! One issue -- can we accommodate updating the pngcheck-ruby version without changing pngcheck? (e.g. Ruby bug fix). Thanks!

Yep It's possible, but manually:
1. Fixate the value of `PNGCHECK_VERSION` to the exact version in `ext/layout.rb`
2. Update `lib/pngcheck/version.rb`

For the next automated version from `pngcheck` it will update `PNGCHECK_VERSION` to `PngCheck::VERSION`
